site_name: dropboxignore
site_description: dropboxignore documentation page
site_author: Panagiotis Simakis

theme:
  name: material
  custom_dir: 'docs/overrides'
  logo: static/icons/256.png
  favicon: static/icons/64.png
  palette:
    primary: blue
  features:
    - navigation.instant
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/sp1thas/dropboxignore/

nav:
  - 'Home': 'index.md'
  - 'Installation': 'installation.md'
  - 'Get started': 'getting-started.md'
  - 'CLI': 'cli.md'
  - 'Development':
      - Development: 'development.md'
      - Contributing: 'contributing.md'
      - Testing: 'testing.md'

extra:
  version:
    provider: mike