when:
  - event: push
  - path:
      include:
        - 'docs/**'

steps:
  - name: build
    image: woodpeckerci/plugin-mkdocs:minimal
    settings:
      pip_install_file: ./docs/requirements.txt
  - name: publish
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1
    settings:
      folder: site
      ssh_key:
        from_secret: codeberg-ssh-key
    when:
      - branch: master

depends_on:
  - checkout-code