when:
  - event: push

steps:
  - name: run-pre-commit-hooks
    image: sp1thas92/woodpecker-ci-pre-commit-runner:0.1.0
    settings:
      args: "--all-files"
      skip: "shellcheck,docker-compose-check"
