when:
  - branch: release/*

steps:
  update-version-file:
    image: alpine/git:latest
    environment:
      CODEBERG_SSH_KEY:
        from_secret: codeberg-ssh-key
    commands:
      - VERSION="${CI_COMMIT_BRANCH#release/}"
      # prepare ssh
      - apk add --no-cache openssh-client
      - mkdir -p ~/.ssh
      - echo "$CODEBERG_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      # trust Codeberg host key (you could hard-code known_hosts instead)
      - ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
      # version bump
      - echo -n "$VERSION-${CI_COMMIT_SHA:0:8}" > /tmp/VERSION
      - git config --global user.email "ci-bot@local"
      - git config --global user.name "Woodpecker CI"
      # fetch & switch to default branch
      - git fetch --all --prune
      - git checkout -B "${CI_REPO_DEFAULT_BRANCH}" "origin/${CI_REPO_DEFAULT_BRANCH}"
      - cp /tmp/VERSION src/lib/modules/VERSION
      # update the version file only if changed
      - git add src/lib/modules/VERSION
      - git commit -m "Update VERSION [skip ci]"
      # push via SSH
      - git push git@codeberg.org:${CI_REPO_OWNER}/${CI_REPO_NAME}.git "${CI_REPO_DEFAULT_BRANCH}"
      - git tag -f $VERSION
      - git push git@codeberg.org:${CI_REPO_OWNER}/${CI_REPO_NAME}.git $VERSION