name: dropboxignore
base: core18
adopt-info: get-version
summary: It's all about the missing .dropboxignore file.
description: |
  Exclude files from dropbox using glob patterns and take advantage of existing .gitignore files.
  This is a simple shell script that can be used to ignore files from dropbox using glob patterns, .dropboxignore files and the already existing .gitignorefiles. The shell script uses this approach to ignore the matched files.
icon: icons/256.png
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: [amd64, i386, arm64, armhf, ppc64el, s390x]

apps:
  dropboxignore:
    command: ./src/bin/cli.sh
    plugs:
      - home

parts:

  get-version:
    build-packages:
      - curl
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(curl -sSL https://raw.githubusercontent.com/sp1thas/dropboxignore/master/src/bin/cli.sh | grep -oP '^VERSION=(.*)$' | sed -r 's/^VERSION=//')"

  main-part:
    stage-packages:
      - attr
    source-type: git
    source: https://github.com/sp1thas/dropboxignore.git
    plugin: dump

