name: Daily stats

on:
  schedule:
    - cron: "1 9 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      - name: Install os dependencies
        run: sudo apt update && sudo apt install curl jq git
      
      - name: Create stats file
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/sp1thas/dropboxignore/master/src/utils/stats.sh)" '${{ secrets.GITHUB_TOKEN }}'
